### ISSUE TITLE
Error at checkout

### ISSUE THREAD

**Issue by MSiliunas** [eshoper/magento2-lpexpress#1]
I started receiving an error in checkout. I have installed the newest version of your module. What could be causing this?
Magento ver. 2.2.8

Exception from apache2 error.log:
```
[Sat Dec 21 22:52:40.805470 2019] [php7:error] [pid 22856] [client 127.0.0.1:34710] PHP Fatal error:  Uncaught Error: Call to a member function getLpexpressTerminal() on null in /var/www/public_html/app/code/Eshoper/LPExpress/Model/Checkout/ShippingInformationManagementPlugin.php:49
Stack trace:
#0 /var/www/public_html/vendor/magento/framework/Interception/Interceptor.php(121): Eshoper\\LPExpress\\Model\\Checkout\\ShippingInformationManagementPlugin->beforeSaveAddressInformation(Object(Magento\\Checkout\\Model\\ShippingInformationManagement\\Interceptor), '239', Object(Magento\\Checkout\\Model\\ShippingInformation))
#1 /var/www/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Checkout\\Model\\ShippingInformationManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}('239', Object(Magento\\Checkout\\Model\\ShippingInformation))
#2 /var/www/public_html/generated/code/Magento/Checkout/Model/ShippingInformationManagement/Interceptor.php(26): Magento\\Checkout\\Model\\ShippingInformationManagement\\Interceptor->___callPlugins('saveAddr in /var/www/public_html/app/code/Eshoper/LPExpress/Model/Checkout/ShippingInformationManagementPlugin.php on line 49, referer: https://local.dev/checkout/
```

**Comment by eshoper** [comment]
Please check if you have any other shipping modules that is overriding `shipping-save-processor`.
You could check directories like for example `app\code\Namespace\Module\view\frontend\web\js\shipping-save-processor-default-override.js`.

If there is, these files needs to load `payload-extender` so you need to edit these files. If you need reference how to load it, you can check in `vendor\magento\module-checkout\view\frontend\web\js\model\shipping-save-processor\default.js`. When you load the `playload-extender` redeploy your static content and everything should start working. If you need assistance please contact us directly lpexpress@eshoper.lt.

**Comment by MSiliunas** [comment]
I found the issue. It was exactly what you said.
Thanks!
